//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// 一个数据源
/// </summary>
public class HtmlDataSource
{
	public virtual string Encoding
	{
		get;
		set;
	}

	public virtual Uri Uri
	{
		get;
		set;
	}

}

