//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// 科目下的模块
/// </summary>
public class SubjectModule
{
	public virtual int Id
	{
		get;
		set;
	}

	public virtual Type Handler
	{
		get;
		set;
	}

	public virtual Subject Subject
	{
		get;
		set;
	}

	public virtual HtmlDataSource HtmlDataSource
	{
		get;
		set;
	}

}

