//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Serialization;

namespace SweetFly.Job.Models.Cmr
{

    /// <summary>
    /// 一个数据源
    /// </summary>
    [Serializable]
    public class HtmlDataSource
    {
        [XmlAttribute("Encoding")]
        public string Encoding { get; set; }

        public string Uri { get; set; }

    }

}

