//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Serialization;


namespace SweetFly.Job.Models.Cmr
{

    /// <summary>
    /// 科目下的模块
    /// </summary>
    [Serializable]
    public class SubjectModule
    {
        [XmlAttribute("Id")]
        public int Id { get; set; }

        [XmlAttribute("Handler")]
        public string Handler { get; set; }

        [XmlIgnore]
        public Type HandlerType
        {
            get
            {
                return Type.GetType(Handler);
            }
        }

        public HtmlDataSource HtmlDataSource { get; set; }

    }



}