//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Serialization;


namespace SweetFly.Job.Models.Cmr
{

    /// <summary>
    /// 科目
    /// </summary>
    [Serializable]
    public class Subject
    {
        /// <summary>
        /// 标识
        /// </summary>
        [XmlAttribute("Id")]
        public int Id { get; set; }

        [XmlAttribute("Enabled")]
        public bool Enabled { get; set; }

        public LoginInfo LoginInfo { set; get; }

        public List<SubjectModule> SubjectModules { get; set; }

    }
}

